#ifndef PRNG_MODEL_H
#define PRNG_MODEL_H

#include <cstdint>
#include <cstddef>
#include <vector>

/**
 * PRNG Model — Kolmogorov-style compression for pseudorandom data.
 *
 * Detects if input data was generated by a known PRNG algorithm
 * (currently: glibc TYPE_3 rand()) and compresses it to just
 * the algorithm ID + seed + length.
 *
 * This exploits the gap between Shannon entropy (≈8.0 bits/byte,
 * statistically random) and Kolmogorov complexity (≈14 bytes,
 * a short program generates the whole file).
 *
 * The glibc TYPE_3 PRNG uses an additive feedback generator with
 * a 31-word state table:
 *   - Init: state[i] = (16807 * state[i-1]) mod (2^31 - 1)
 *   - Warm-up: 310 iterations
 *   - Recurrence: state[fptr] += state[rptr], output = state[fptr] >> 1
 *   - Output byte: rand() & 0xFF
 */
class PrngModel {
public:
    enum Algorithm : uint8_t {
        GLIBC_RAND = 0,  // glibc TYPE_3 rand() (additive feedback, 31-word state)
    };

    struct DetectionResult {
        bool detected;
        Algorithm algorithm;
        uint32_t seed;
    };

    /**
     * Try to detect if data was generated by a known PRNG.
     * Tests glibc rand() with seeds 0..max_seed.
     * Uses a two-phase approach: quick match on first prefix_len bytes,
     * then full verification on match.
     */
    static DetectionResult detect(const std::vector<uint8_t>& data,
                                  uint32_t max_seed = 65535,
                                  size_t prefix_len = 64);

    /**
     * Generate data using the specified PRNG algorithm and seed.
     */
    static std::vector<uint8_t> generate(Algorithm algo,
                                         uint32_t seed,
                                         size_t length);

private:
    /**
     * Simulate glibc TYPE_3 rand() and produce `length` output bytes.
     * Each byte is rand() & 0xFF.
     */
    static std::vector<uint8_t> generate_glibc_rand(uint32_t seed, size_t length);
};

#endif // PRNG_MODEL_H
